version: '3.8'

services:
  datapulse_db:
    image: postgres:15-alpine
    container_name: datapulse_postgres_dw
    environment:
      POSTGRES_USER: datapulse_admin
      POSTGRES_PASSWORD: SecretEnterprisePassword123!
      POSTGRES_DB: datapulse_warehouse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
    driver: local

